version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_client
    ports:
      - "8089:80"
    networks:
      - app_net

  server:
    build:
      context: .
      dockerfile: Dockerfile_server
    ports:
      - "8000:8000"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

